variables:
  NET_VERSION: '6.0.x'
  NET_CORE_VERSION: '3.1.x'
  PathToSolution: 'GitTrends.sln'
  PathToGitTrendsCsproj: 'GitTrends/GitTrends.csproj'
  PathToiOSAppCsproj: 'GitTrends.iOS/GitTrends.iOS.csproj'
  PathToUITestsCsproj: 'GitTrends.UITests/GitTrends.UITests.csproj'
  PathToAndroidAppCsproj: 'GitTrends.Android/GitTrends.Android.csproj'
  PathToUnitTestsCsproj: 'GitTrends.UnitTests/GitTrends.UnitTests.csproj'
  PathToAzureFunctionsCsproj: 'GitTrends.Functions/GitTrends.Functions.csproj'
  XcodeVersion: '13.3.1'

trigger:
  branches:
    include:
    - main
  tags:
    include:
    - '*'
  paths:
    exclude:
    - README.md

pr:
  autoCancel: 'true'
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

jobs:
  - job: Build_AzureFunctions
    displayName: Build Azure Functions
    pool: 
      vmImage: windows-latest

    steps:      
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          packageType: 'sdk'
          version: '$(NET_VERSION)'

      - task: VSBuild@1
        displayName: 'Build Azure Functions'
        inputs:
          solution: '$(PathToAzureFunctionsCsproj)'
          configuration: 'Release'
          msbuildArgs: '/restore'

  - job: Build_UITests
    displayName: Build UI Tests
    pool: 
      vmImage: windows-latest

    steps:      
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          packageType: 'sdk'
          version: '$(NET_VERSION)'

      - task: VSBuild@1
        displayName: 'Build UI Tests'
        inputs:
          solution: '$(PathToUITestsCsproj)'
          configuration: 'Release'
          msbuildArgs: '/restore'

  - job: Build_iOS_App
    displayName: Build iOS App
    pool: 
      vmImage: macos-latest

    steps:      
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          packageType: 'sdk'
          version: '$(NET_VERSION)'

      - task: InstallAppleCertificate@2
        inputs:
          certSecureFile: Certificates.p12
          certPwd: $(APPLECERTIFICATEPASSWORD)
          deleteCert: true

      - task: InstallAppleProvisioningProfile@1
        inputs:
          provisioningProfileLocation: 'secureFiles'
          provProfileSecureFile: GitTrends_Development_Profile.mobileprovision
          removeProfile: true

      - task: CmdLine@2
        displayName: 'Boots: Install Mono'
        inputs: 
          script: |
            dotnet tool install --global boots --prerelease
            boots --alpha Mono

      - task: NuGetCommand@2
        displayName: 'Restore NuGet Packages'
        inputs:
          command: 'restore'
          restoreSolution: '$(PathToSolution)'
          feedsToUse: 'select'

      - task: CmdLine@2
        displayName: 'Build GitTrends .NET Standard Project'
        inputs:
          script: 'dotnet build $(PathToGitTrendsCsproj) -c Release'

      - task: XamariniOS@2
        displayName: 'Build iOS App'
        inputs:
          solutionFile: '$(PathToiOSAppCsproj)'
          configuration: 'Release'
          packageApp: true

  - job: Build_Android_App
    displayName: Build Android App
    pool: 
      vmImage: windows-latest

    steps:      
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          packageType: 'sdk'
          version: '$(NET_VERSION)'

      - task: VSBuild@1
        displayName: 'Build Android App'
        inputs:
          solution: '$(PathToAndroidAppCsproj)'
          configuration: 'Release'
          msbuildArgs: '/restore'

  - job: Build_UnitTests
    displayName: Build Unit Tests
    pool: 
      vmImage: windows-latest

    steps:      
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          packageType: 'sdk'
          version: '$(NET_VERSION)'

      - task: VSBuild@1
        displayName: 'Build Unit Tests'
        inputs:
          solution: '$(PathToUnitTestsCsproj)'
          configuration: 'Release'
          msbuildArgs: '/restore'

  - job: Run_UnitTests
    displayName: Run Unit Tests
    dependsOn: [Build_UnitTests, Build_Android_App, Build_iOS_App, Build_UITests]
    pool: 
      vmImage: macos-latest

    steps:      
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          packageType: 'sdk'
          version: '$(NET_VERSION)'

      - task: UseDotNet@2
        displayName: 'Install .NET Core 3.1 SDK'
        inputs:
          packageType: 'sdk'
          version: '$(NET_CORE_VERSION)'

      - task: CmdLine@2
        displayName: 'Inject API Keys'
        inputs:
          script: |
            set -e

            AzureConstantsFile=`find . -name AzureConstants.cs | head -1`
            echo AzureConstantsFile = $AzureConstantsFile

            sed -i '' "s/GetTestTokenApiKey = \"\"/GetTestTokenApiKey = \"$(GETTESTTOKENAPIKEY)\"/g" "$AzureConstantsFile"  
            sed -i '' "s/GetAppCenterApiKeysKey = \"\"/GetAppCenterApiKeysKey = \"$(GETAPPCENTERAPIKEYSKEY)\"/g" "$AzureConstantsFile"
            sed -i '' "s/GetSyncFusionInformationApiKey = \"\"/GetSyncFusionInformationApiKey = \"$(GETSYNCFUSIONINFORMATIONAPIKEY)\"/g" "$AzureConstantsFile"
            sed -i '' "s/GetNotificationHubInformationApiKey = \"\"/GetNotificationHubInformationApiKey = \"$(GETNOTIFICATIONHUBINFORMATIONAPIKEY)\"/g" "$AzureConstantsFile"
            sed -i '' "s/#error Missing API Keys/\/\/#error Missing API Keys/g" "$AzureConstantsFile"

      - task: CmdLine@2
        displayName: 'Run Unit Tests'
        inputs:
          script: 'dotnet test $(PathToUnitTestsCsproj) -c Release'